// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHfSQ_a23ANBxL46POMC0k2ymcS7wrMXU',
    appId: '1:188825311164:web:b674bc7b5903b89d0dfdb9',
    messagingSenderId: '188825311164',
    projectId: 'cu-fest',
    authDomain: 'cu-fest.firebaseapp.com',
    storageBucket: 'cu-fest.appspot.com',
    measurementId: 'G-CFFE8DD79V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp8J6bRfNFfkhsGyPW_GJl25M_F3Hdug8',
    appId: '1:188825311164:android:5d04825619f799ec0dfdb9',
    messagingSenderId: '188825311164',
    projectId: 'cu-fest',
    storageBucket: 'cu-fest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByiec1gJ8oHYdt3r440m6nGl-KEExajHE',
    appId: '1:188825311164:ios:7aa6adae925c171d0dfdb9',
    messagingSenderId: '188825311164',
    projectId: 'cu-fest',
    storageBucket: 'cu-fest.appspot.com',
    iosBundleId: 'com.example.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByiec1gJ8oHYdt3r440m6nGl-KEExajHE',
    appId: '1:188825311164:ios:7bb01959eeef7b410dfdb9',
    messagingSenderId: '188825311164',
    projectId: 'cu-fest',
    storageBucket: 'cu-fest.appspot.com',
    iosBundleId: 'com.example.user.RunnerTests',
  );
}
