// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB83Rf7iPGYxq9lf0G5J-l0ZPv1dfFyWAk',
    appId: '1:164382157909:web:42fcb62e04b22e667cf8dc',
    messagingSenderId: '164382157909',
    projectId: 'cufest-test',
    authDomain: 'cufest-test.firebaseapp.com',
    storageBucket: 'cufest-test.appspot.com',
    measurementId: 'G-6D4KGW842X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBvRLnXS5af2CtqOgeZJf4Z0c8R1HmK8A',
    appId: '1:164382157909:android:72bec74f45fd15af7cf8dc',
    messagingSenderId: '164382157909',
    projectId: 'cufest-test',
    storageBucket: 'cufest-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_bMzUyQrkhW4yZ72ZbWJLkMIEeQTudyY',
    appId: '1:164382157909:ios:84b8a906b3abd4347cf8dc',
    messagingSenderId: '164382157909',
    projectId: 'cufest-test',
    storageBucket: 'cufest-test.appspot.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_bMzUyQrkhW4yZ72ZbWJLkMIEeQTudyY',
    appId: '1:164382157909:ios:53cf40b2aa075ce37cf8dc',
    messagingSenderId: '164382157909',
    projectId: 'cufest-test',
    storageBucket: 'cufest-test.appspot.com',
    iosBundleId: 'com.example.admin.RunnerTests',
  );
}
