// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3cWE4_1pD9zY3Lowy4GtjZiqHNeHhjFk',
    appId: '1:961313199501:web:c6ec86887df713d46059c4',
    messagingSenderId: '961313199501',
    projectId: 'cu-fest-test',
    authDomain: 'cu-fest-test.firebaseapp.com',
    storageBucket: 'cu-fest-test.appspot.com',
    measurementId: 'G-TDCSEP5CHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRVQmUo6lo3RrUICbwlxGkAMNUSgaUZvg',
    appId: '1:961313199501:android:0d7b225fb5c610ee6059c4',
    messagingSenderId: '961313199501',
    projectId: 'cu-fest-test',
    storageBucket: 'cu-fest-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPM-uM5OGRQsYUi-pCHJ-xScnu9oWA-Tg',
    appId: '1:961313199501:ios:236a0e5c20ab7fe16059c4',
    messagingSenderId: '961313199501',
    projectId: 'cu-fest-test',
    storageBucket: 'cu-fest-test.appspot.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPM-uM5OGRQsYUi-pCHJ-xScnu9oWA-Tg',
    appId: '1:961313199501:ios:bc1d896de37b5e866059c4',
    messagingSenderId: '961313199501',
    projectId: 'cu-fest-test',
    storageBucket: 'cu-fest-test.appspot.com',
    iosBundleId: 'com.example.admin.RunnerTests',
  );
}
